# Generated by Django 2.1.2 on 2018-10-11 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('minimum_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deadline', models.DateTimeField()),
                ('banned', models.BooleanField(default=False)),
                ('due', models.BooleanField(default=False)),
                ('current_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bidders', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('current_bidder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auction-bidder+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction-seller+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
