# Generated by Django 2.1.2 on 2018-10-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20181019_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
