# Generated by Django 2.1.2 on 2018-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
